In [96]:
%load_ext autoreload
%autoreload 2
import numpy as np
import tensorflow as tf
from phaunos_ml.utils.dataug_utils import Mixup

tf.enable_eager_execution()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [112]:
feat_size = 2
batch_size = 3

# Fake training data with 8 examples with shape (1,1,2) (NCHW format, i.e. channel_first)
n_train = 8
train_dataset = tf.data.Dataset.from_tensor_slices((np.random.rand(n_train, 1, 1, feat_size), 
                                                    np.random.choice([0,1], n_train)))
train_dataset = train_dataset.repeat()
train_dataset = train_dataset.batch(batch_size)

# Fake augmentation data with 5 examples with shape (1,1,2) (NCHW format, i.e. channel_first)
n_aug = 5
aug_dataset = tf.data.Dataset.from_tensor_slices((np.random.rand(n_aug, 1, 1, feat_size), 
                                                  np.random.choice([0,1], n_aug)))
aug_dataset = aug_dataset.repeat()
aug_dataset = aug_dataset.batch(batch_size)

dataset = tf.data.Dataset.zip((train_dataset, aug_dataset))

In [95]:
w = tf.cast(tf.distributions.Uniform().sample(sample_shape=batch_size), tf.float64)
w

<tf.Tensor: id=679, shape=(3,), dtype=float64, numpy=array([0.69391787, 0.07863522, 0.0389924 ])>

In [113]:
aug = Mixup()
dataset = dataset.map(lambda dataset1, dataset2: aug.process(dataset1[0], dataset1[1], dataset2[0], dataset2[1], batch_size))

Tensor("BroadcastTo:0", shape=(3, 1, 1, 2), dtype=float64)
Tensor("args_0:0", shape=(?, 1, 1, 2), dtype=float64)
Tensor("args_2:0", shape=(?, 1, 1, 2), dtype=float64)


In [114]:
count = 0
for b, l in dataset:
    if count > 1:
        break
    print("********************************")
    print(b)
    print("***")
    print(l)
    count += 1

********************************
tf.Tensor(
[[[[0.77460851 0.7670947 ]]]


 [[[0.04232765 0.71883306]]]


 [[[0.69101746 0.51355938]]]], shape=(3, 1, 1, 2), dtype=float64)
***
tf.Tensor([ True False False], shape=(3,), dtype=bool)
********************************
tf.Tensor(
[[[[0.37817771 0.67621061]]]


 [[[0.4203652  0.37905711]]]


 [[[0.62409657 0.1893447 ]]]], shape=(3, 1, 1, 2), dtype=float64)
***
tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [7]:
aug = Mixup()
dataset = dataset.map(aug)

In [8]:
count = 0
for d in dataset:
    if count > 1:
        break
    print("********************************")
    print(d[0])
    print("***")
    print(d[1])
    count += 1

********************************
Tensor("IteratorGetNext_3:0", shape=(?, 1, 1, 2), dtype=float64)
***
Tensor("IteratorGetNext_3:1", shape=(?,), dtype=int64)
********************************
Tensor("IteratorGetNext_4:0", shape=(?, 1, 1, 2), dtype=float64)
***
Tensor("IteratorGetNext_4:1", shape=(?,), dtype=int64)


In [19]:
tf.distributions.Uniform().sample()

<tf.Tensor: id=243, shape=(), dtype=float32, numpy=0.03947401>

In [16]:
dataset

<DatasetV1Adapter shapes: (((?, 1, 1, 2), (?,)), ((?, 1, 1, 2), (?,))), types: ((tf.float64, tf.int64), (tf.float64, tf.int64))>

In [84]:
a = tf.constant([1,10])
b = tf.constant([[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]]])

In [85]:
a = tf.expand_dims(a, -1)
a = tf.expand_dims(a, -1)
a = tf.broadcast_to(a, (2,3,3))

In [86]:
a

<tf.Tensor: id=473, shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]], dtype=int32)>

In [82]:
a = tf.broadcast_to(tf.expand_dims(a, -1), (2,3,3))

In [88]:
tf.shape(a)

SyntaxError: can't use starred expression here (<ipython-input-88-1d8890052bee>, line 4)

In [110]:
tf.bitwise.bitwise_or([0,0,1],[1,0,1])

<tf.Tensor: id=1057, shape=(3,), dtype=int32, numpy=array([1, 0, 1], dtype=int32)>